Repository GSG-G7/sitspot, pull requests merged in 2019-10, with the labels that each got.

#10 Update README.md
  README.md
Labels: Awaiting Review

#35 25 front file structure with eslint
  .eslintrc.js
  .gitignore
  client/.eslintrc.js
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App/App.test.js
  client/src/App/index.js
  client/src/App/style.css
  client/src/assets/index.js
  client/src/components/index.js
  client/src/index.css
  client/src/index.js
  client/src/pages/index.js
  client/src/services/api.js
  client/src/utils/index.js
  package-lock.json
  package.json
Labels: Awaiting Review

#36 added package json scripts
  package-lock.json
  package.json
Labels: Approved

#41 15 button
  client/src/App/index.js
  client/src/components/Button/index.js
  client/src/components/Button/style.css
  client/src/components/index.js
Labels: for merge

#42 fixed proptypes for Button component
  client/src/components/Button/index.js
Labels: for merge

#37 Floating action button done
  client/src/App/style.css
  client/src/components/Fab/index.js
  client/src/components/Fab/style.css
  client/src/components/index.js
  client/src/index.css
  client/src/index.js
Labels: for merge

#44 make component menu
  client/src/components/Menu/index.css
  client/src/components/Menu/index.js
  client/src/components/index.js
  client/src/index.js
Labels: Awaiting Review

#40 keyword list
  client/.eslintrc.js
  client/src/components/Keywords/fakeData.js
  client/src/components/Keywords/index.css
  client/src/components/Keywords/index.js
  client/src/components/index.js
Labels: Awaiting Review

#50 footer component
  client/src/components/Footer/index.css
  client/src/components/Footer/index.js
  client/src/components/index.js
Labels: Awaiting Review

#47 32 keyword
  client/src/App/index.js
  client/src/assets/Keywords/commitment.png
  client/src/assets/Keywords/family.png
  client/src/assets/Keywords/immersion.png
  client/src/assets/Keywords/index.js
  client/src/assets/Keywords/interaction.png
  client/src/assets/Keywords/kid.png
  client/src/assets/Keywords/luxury.png
  client/src/assets/Keywords/nature.png
  client/src/assets/Keywords/rural.png
  client/src/assets/Keywords/social.png
  client/src/assets/Keywords/solo.png
  client/src/assets/Keywords/staff.png
  client/src/assets/Keywords/urban.png
  client/src/assets/Keywords/vegan.png
  client/src/assets/Keywords/vegetarian.png
  client/src/assets/Keywords/wellbeing.png
  client/src/assets/Keywords/wild.png
  client/src/components/Keywords/fakeData.js
  client/src/components/Keywords/index.js
  client/src/components/MagicalFactor/index.js
  client/src/components/MagicalFactor/style.css
  client/src/components/index.js
  client/src/index.css
  client/src/staticDataSet/keywords.js
Labels: Awaiting Review

#55 renamed keywords Components into KeywordsList
  client/src/components/KeywordList/index.css
  client/src/components/KeywordList/index.js
  client/src/components/index.js
  client/src/staticDataSet/keywords.js
Labels: Awaiting Review

#52 make the carousel component
  client/src/components/ImageCarousel/fakeData.js
  client/src/components/ImageCarousel/index.js
  client/src/components/ImageCarousel/style.css
  client/src/components/index.js
Labels: Awaiting Review

#49 SearchResult component is created and styled
  client/src/assets/areas/hotel.png
  client/src/assets/areas/restaurant.png
  client/src/assets/images/placeimg.png
  client/src/assets/index.js
  client/src/components/SearchResult/fakeData.js
  client/src/components/SearchResult/index.js
  client/src/components/SearchResult/style.css
  client/src/components/index.js
Labels: Awaiting Review
