Repository GSG-G7/sitspot, pull requests merged in 2019-11, with the labels that each got.

#62 Layout
  client/src/App/index.js
  client/src/App/style.css
  client/src/components/Footer/index.css
  client/src/components/Footer/index.js
  client/src/components/Header/style.css
  client/src/components/Layout/index.js
  client/src/components/Menu/index.js
  client/src/components/index.js
  client/src/index.css
Labels: Awaiting Review

#63 FAQ Page && component CollapsePanel
  client/src/assets/FAQ-header.png
  client/src/components/CollapsePanel/index.css
  client/src/components/CollapsePanel/index.js
  client/src/components/index.js
  client/src/index.js
  client/src/pages/FAQ/fakeData.js
  client/src/pages/FAQ/index.css
  client/src/pages/FAQ/index.js
  client/src/pages/index.js
Labels: Awaiting Review

#59 about us page
  client/src/assets/about-img-1.png
  client/src/assets/founder.JPG
  client/src/components/CollapsePanel/index.js
  client/src/pages/FAQ/index.js
  client/src/pages/aboutUs/fakeData.js
  client/src/pages/aboutUs/index.css
  client/src/pages/aboutUs/index.js
  client/src/pages/index.js
Labels: Awaiting Review

#65 added a rule that prevents opening a block just to return
  client/.eslintrc.js
  client/src/components/Footer/index.js
  client/src/components/KeywordList/index.js
  client/src/components/Menu/index.js
Labels: Awaiting Review

#58 19 review component
  client/.eslintrc.js
  client/src/App/style.css
  client/src/components/MagicalFactor/index.js
  client/src/components/MagicalFactor/style.css
  client/src/components/Review/index.js
  client/src/components/Review/style.css
  client/src/components/Review/subcomponent/ProfileDetails.js
  client/src/components/index.js
  client/src/index.css
Labels: Awaiting Review

#60 search page
  client/src/components/KeywordList/index.js
  client/src/components/Search/index.js
  client/src/components/SearchResult/fakeData.js
  client/src/components/SearchResult/index.js
  client/src/index.css
  client/src/pages/Search/index.js
  client/src/pages/Search/style.css
  client/src/pages/index.js
Labels: Awaiting Review

#67 11 back fs
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/middleware/index.js
  server/controllers/utils/index.js
  server/index.js
  server/routes/index.js
  tests/index.test.js
Labels: Awaiting Review

#70 added airtable configuration
  package.json
  server/models/config.js
  server/models/index.js
  server/models/queries/index.js
Labels: Awaiting Review

#61 Typeform page
  client/package-lock.json
  client/package.json
  client/src/components/Footer/index.js
  client/src/pages/AboutUs/fakeData.js
  client/src/pages/AboutUs/index.css
  client/src/pages/AboutUs/index.js
  client/src/pages/AddReview/index.js
  client/src/pages/AddReview/style.css
  client/src/pages/AddReview/urls.js
  client/src/pages/index.js
Labels: Awaiting Review

#64 24 home page
  client/src/assets/images/home-background.jpg
  client/src/assets/images/icon-sign.svg
  client/src/assets/images/logo.svg
  client/src/assets/images/logo2.svg
  client/src/components/ImageCarousel/fakeData.js
  client/src/components/ImageCarousel/style.css
  client/src/index.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.css
  client/src/pages/index.js
Labels: Awaiting Review

#76 install supertest to test routes
  package-lock.json
  package.json
Labels: Awaiting Review

#71 keywrods route get
  package-lock.json
  package.json
  server/controllers/index.js
  server/controllers/routes/getKeywords.js
  server/controllers/routes/index.js
  server/models/queries/getKeywords.js
  server/models/queries/index.js
  server/router/index.js
  tests/index.test.js
  tests/routes/getKeywords.test.js
  tests/routes/index.js
Labels: Awaiting Review, B.E.Routes, Backend

#79 9 place and reviews
  package.json
  server/controllers/errors/error.js
  server/controllers/errors/index.js
  server/controllers/index.js
  server/controllers/routes/index.js
  server/controllers/routes/placeAndReviews.js
  server/models/queries/getPlace.js
  server/models/queries/getPlaceReviews.js
  server/models/queries/index.js
  server/router/index.js
  tests/routes/getPlaceReviews.test.js
  tests/routes/index.js
Labels: Awaiting Review, Backend

#78 34 single place page
  client/src/App/style.css
  client/src/assets/images/back-single.png
  client/src/assets/images/left-arrow.svg
  client/src/assets/images/plus.svg
  client/src/components/Fab/style.css
  client/src/components/ImageCarousel/index.js
  client/src/components/ImageCarousel/style.css
  client/src/components/MagicalFactor/style.css
  client/src/components/Review/index.js
  client/src/components/Review/style.css
  client/src/pages/SinglePlace/FakeData.js
  client/src/pages/SinglePlace/index.js
  client/src/pages/SinglePlace/style.css
  client/src/pages/index.js
Labels: Awaiting Review

#72 8 search route
  client/src/staticDataSet/keywords.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/routes/index.js
  server/controllers/routes/search.js
  server/models/queries/index.js
  server/models/queries/search.js
  server/router/index.js
  tests/search.test.js
Labels: Awaiting Review, in-progress

#80 28 add sitspot
  client/package.json
  client/src/assets/question-1.png
  client/src/components/StepsQuestions/UploadImg.js
  client/src/components/StepsQuestions/index.css
  client/src/components/StepsQuestions/index.js
  client/src/components/index.js
  client/src/pages/addNewSitSpot/fakeData.js
  client/src/pages/addNewSitSpot/index.css
  client/src/pages/addNewSitSpot/index.js
  client/src/pages/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/errors/error.js
  server/controllers/errors/index.js
  server/controllers/index.js
  server/controllers/routes/index.js
  server/controllers/routes/place.js
  server/controllers/routes/placeAndReviews.js
  server/controllers/utils/index.js
  server/controllers/utils/upload.js
  server/controllers/validation/index.js
  server/controllers/validation/place.js
  server/models/config.js
  server/models/queries/addPlace.js
  server/models/queries/index.js
  server/router/index.js
Labels: Awaiting Review

#84 remove the global override style class
  client/src/components/StepsQuestions/index.css
  client/src/components/StepsQuestions/index.js
  client/src/pages/addNewSitSpot/index.css
Labels: Awaiting Review

#82 30 react router
  client/src/App/index.js
  client/src/components/Header/index.js
  client/src/components/ImageCarousel/index.js
  client/src/components/Menu/index.js
  client/src/components/Review/index.js
  client/src/components/Search/index.js
  client/src/components/SearchResult/index.js
  client/src/components/StepsQuestions/index.js
  client/src/pages/AddReview/index.js
  client/src/pages/Home/index.js
  client/src/pages/Search/index.js
  client/src/pages/SinglePlace/FakeData.js
  client/src/pages/SinglePlace/index.js
  client/src/pages/addNewSitSpot/index.css
  client/src/pages/addNewSitSpot/index.js
  client/src/pages/index.js
  client/src/services/api.js
  client/src/services/api/index.js
  server/controllers/routes/search.js
  server/models/queries/search.js
Labels: Awaiting Review, in-progress

#92 86 initial feedback small fast fixes
  .gitattributes
  client/src/components/Button/index.js
  client/src/components/Button/style.css
  client/src/components/Menu/index.css
  client/src/components/Menu/index.js
  client/src/components/Review/style.css
  client/src/components/Review/subcomponent/ProfileDetails.js
  client/src/components/Search/index.js
  client/src/components/Search/style.css
  client/src/pages/Home/index.js
  client/src/pages/Search/index.js
  client/src/pages/SinglePlace/index.js
  server/controllers/utils/formatReviews.js
  server/models/cached/keywords.js
Labels: Awaiting Review

#98 make the image random for each load
  client/src/pages/Home/images.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.css
  client/src/pages/SinglePlace/index.js
Labels: Awaiting Review

#97 Update content for faq & aboutus
  client/src/components/CollapsePanel/index.js
  client/src/pages/AboutUs/fakeData.js
  client/src/pages/AboutUs/index.css
  client/src/pages/FAQ/fakeData.js
  client/src/pages/FAQ/index.css
  client/src/pages/FAQ/index.js
Labels: Awaiting Review

#107 display a message when the sitspots not found
  client/src/pages/Search/index.js
  client/src/pages/Search/style.css
Labels: Awaiting Review, Frontend

#111 110 iphone5 search component
  client/src/components/Search/style.css
Labels: Awaiting Review, Frontend

#103 Add welcome's step in add new place page
  client/src/components/StepsQuestions/UploadImg.js
  client/src/components/StepsQuestions/index.css
  client/src/components/StepsQuestions/index.js
  client/src/pages/FAQ/fakeData.js
  client/src/pages/addNewSitSpot/fakeData.js
  client/src/pages/addNewSitSpot/index.css
  client/src/pages/addNewSitSpot/index.js
  client/src/utils/addPlaceValidation.js
  client/src/utils/index.js
  package.json
  server/controllers/routes/place.js
  server/models/queries/addPlace.js
Labels: Awaiting Review

#114 Review image slider
  client/src/components/Review/index.js
  client/src/pages/AddReview/index.js
  client/src/pages/Home/index.js
  client/src/pages/SinglePlace/index.js
Labels: Awaiting Review

#115 113 images optimization
  client/src/assets/images/aboutus-back (copy).jpg
  client/src/assets/images/aboutus-back.jpg
  client/src/assets/images/addrecom.png
  client/src/components/Header/style.css
  client/src/pages/AboutUs/index.css
  client/src/pages/FAQ/index.css
  client/src/pages/Search/style.css
  client/src/pages/addNewSitSpot/index.css
Labels: Awaiting Review

#118 Fix FAQ && addPlace page
  client/src/components/StepsQuestions/index.css
  client/src/pages/addNewSitSpot/index.css
Labels: Awaiting Review

#121 search eat type fix
  client/src/components/Search/index.js
Labels: for merge

#122 converted the component to class so on unmount i hide the form
  client/src/pages/AddReview/index.js
Labels: for merge

#119 Fix spinner message
  client/src/pages/Search/index.js
Labels: Awaiting Review
